apiVersion: v1
kind: Namespace
metadata:
  name: gesco
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gesco-config
  namespace: gesco
data:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka"
  SPRING_CONFIG_URI: "http://config-server:8888"
