sonar.projectKey=gesco-microservices
sonar.projectName=Gesco Microservices
sonar.projectVersion=1.0

# Base directory for the modules
sonar.modules=services/config-server,services/discovery-server,services/service-audit,services/service-document-ged,services/service-inventory,services/service-notification,services/service-payment,services/service-pricing,services/service-sales

# Assuming Maven structure for all services
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# NestJS services can be added if applicable
# services/api-gateway.sonar.sources=src
# services/api-gateway.sonar.tests=src/test
