@echo off
echo Initializing Gateway...
call npx -y @nestjs/cli new gateway --skip-install --package-manager npm
echo Initializing Inventory Service...
call npx -y @nestjs/cli new inventory-service --skip-install --package-manager npm
