spring.application.name=service-sales
server.port=8083

# Database configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gesco_sales}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}
