apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-pricing
  namespace: gesco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-pricing
  template:
    metadata:
      labels:
        app: service-pricing
    spec:
      containers:
      - name: service-pricing
        image: gesco/service-pricing:latest
        ports:
        - containerPort: 8083
        envFrom:
        - configMapRef:
            name: gesco-config
---
apiVersion: v1
kind: Service
metadata:
  name: service-pricing
  namespace: gesco
spec:
  selector:
    app: service-pricing
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
